# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draft.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 609)
        MainWindow.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settingWidget = QtWidgets.QWidget(self.centralwidget)
        self.settingWidget.setMinimumSize(QtCore.QSize(250, 250))
        self.settingWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settingWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(120, 120, 120);\n"
"}")
        self.settingWidget.setObjectName("settingWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.settingWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.settingLabel_5 = QtWidgets.QLabel(self.settingWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.settingLabel_5.setFont(font)
        self.settingLabel_5.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.settingLabel_5.setObjectName("settingLabel_5")
        self.verticalLayout_10.addWidget(self.settingLabel_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.modelLabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.modelLabel_5.setStyleSheet("font: 75 9pt \"Berlin Sans FB\";\n"
"color: rgb(255, 255, 255);")
        self.modelLabel_5.setObjectName("modelLabel_5")
        self.horizontalLayout_4.addWidget(self.modelLabel_5)
        self.modelCombo_5 = QtWidgets.QComboBox(self.settingWidget)
        self.modelCombo_5.setStyleSheet("QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Agency FB\";\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: white; \n"
"}")
        self.modelCombo_5.setObjectName("modelCombo_5")
        self.modelCombo_5.addItem("")
        self.modelCombo_5.addItem("")
        self.modelCombo_5.addItem("")
        self.modelCombo_5.addItem("")
        self.modelCombo_5.addItem("")
        self.horizontalLayout_4.addWidget(self.modelCombo_5)
        self.loadModelBtn_5 = QtWidgets.QPushButton(self.settingWidget)
        self.loadModelBtn_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.loadModelBtn_5.setObjectName("loadModelBtn_5")
        self.horizontalLayout_4.addWidget(self.loadModelBtn_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.inputLabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.inputLabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.inputLabel_5.setObjectName("inputLabel_5")
        self.horizontalLayout_11.addWidget(self.inputLabel_5)
        self.videoButton_5 = QtWidgets.QToolButton(self.settingWidget)
        self.videoButton_5.setStyleSheet("QToolButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"QToolButton:pressed{\n"
"    background-color: rgb(165, 165, 165);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/视频.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.videoButton_5.setIcon(icon)
        self.videoButton_5.setObjectName("videoButton_5")
        self.horizontalLayout_11.addWidget(self.videoButton_5)
        self.pictureButton_5 = QtWidgets.QToolButton(self.settingWidget)
        self.pictureButton_5.setStyleSheet("QToolButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"QToolButton:pressed{\n"
"    background-color: rgb(165, 165, 165);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pictureButton_5.setIcon(icon1)
        self.pictureButton_5.setObjectName("pictureButton_5")
        self.horizontalLayout_11.addWidget(self.pictureButton_5)
        self.cameraButton_5 = QtWidgets.QToolButton(self.settingWidget)
        self.cameraButton_5.setStyleSheet("QToolButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"QToolButton:pressed{\n"
"    background-color: rgb(165, 165, 165);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/摄像头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton_5.setIcon(icon2)
        self.cameraButton_5.setObjectName("cameraButton_5")
        self.horizontalLayout_11.addWidget(self.cameraButton_5)
        self.detectBtn_5 = QtWidgets.QPushButton(self.settingWidget)
        self.detectBtn_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.detectBtn_5.setObjectName("detectBtn_5")
        self.horizontalLayout_11.addWidget(self.detectBtn_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.loUSlider_5 = QtWidgets.QSlider(self.settingWidget)
        self.loUSlider_5.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 170, 0);\n"
"    width: 10px;\n"
"    height:10px;    \n"
"    margin-top: -4px;  \n"
"    margin-bottom: -4px;\n"
"    border-radius:5px;\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"    background:black;\n"
"    height:3px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"    height:3px;\n"
"    background:white;\n"
"}")
        self.loUSlider_5.setMaximum(100)
        self.loUSlider_5.setPageStep(1)
        self.loUSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.loUSlider_5.setObjectName("loUSlider_5")
        self.gridLayout_13.addWidget(self.loUSlider_5, 1, 1, 1, 1)
        self.loULabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.loULabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.loULabel_5.setObjectName("loULabel_5")
        self.gridLayout_13.addWidget(self.loULabel_5, 0, 0, 1, 1)
        self.loUSpinBox_5 = QtWidgets.QDoubleSpinBox(self.settingWidget)
        self.loUSpinBox_5.setStyleSheet("QDoubleSpinBox{\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-width:1px solid;\n"
"    background-color: rgb(209, 209, 209);\n"
"}")
        self.loUSpinBox_5.setMaximum(1.0)
        self.loUSpinBox_5.setSingleStep(0.01)
        self.loUSpinBox_5.setObjectName("loUSpinBox_5")
        self.gridLayout_13.addWidget(self.loUSpinBox_5, 1, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_13)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.confidenceLabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.confidenceLabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.confidenceLabel_5.setObjectName("confidenceLabel_5")
        self.gridLayout_14.addWidget(self.confidenceLabel_5, 0, 0, 1, 1)
        self.confSpin_5 = QtWidgets.QDoubleSpinBox(self.settingWidget)
        self.confSpin_5.setStyleSheet("QDoubleSpinBox{\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-width:1px solid;\n"
"    background-color: rgb(209, 209, 209);\n"
"}")
        self.confSpin_5.setMaximum(1.0)
        self.confSpin_5.setSingleStep(0.01)
        self.confSpin_5.setObjectName("confSpin_5")
        self.gridLayout_14.addWidget(self.confSpin_5, 1, 0, 1, 1)
        self.confSlider_5 = QtWidgets.QSlider(self.settingWidget)
        self.confSlider_5.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 170, 0);\n"
"    width: 10px;\n"
"    height:10px;    \n"
"    margin-top: -4px;  \n"
"    margin-bottom: -4px;\n"
"    border-radius:5px;\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"    background:black;\n"
"    height:3px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"    height:3px;\n"
"    background:white;\n"
"}")
        self.confSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_5.setObjectName("confSlider_5")
        self.gridLayout_14.addWidget(self.confSlider_5, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_14)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.delayLabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.delayLabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.delayLabel_5.setObjectName("delayLabel_5")
        self.gridLayout_15.addWidget(self.delayLabel_5, 0, 0, 1, 1)
        self.delaySpinBox_5 = QtWidgets.QDoubleSpinBox(self.settingWidget)
        self.delaySpinBox_5.setStyleSheet("QDoubleSpinBox{\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-width:1px solid;\n"
"    background-color: rgb(209, 209, 209);\n"
"}")
        self.delaySpinBox_5.setMaximum(1.0)
        self.delaySpinBox_5.setSingleStep(0.01)
        self.delaySpinBox_5.setObjectName("delaySpinBox_5")
        self.gridLayout_15.addWidget(self.delaySpinBox_5, 1, 0, 1, 1)
        self.delaySlider_5 = QtWidgets.QSlider(self.settingWidget)
        self.delaySlider_5.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 170, 0);\n"
"    width: 10px;\n"
"    height:10px;    \n"
"    margin-top: -4px;  \n"
"    margin-bottom: -4px;\n"
"    border-radius:5px;\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"    background:black;\n"
"    height:3px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"    height:3px;\n"
"    background:white;\n"
"}")
        self.delaySlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.delaySlider_5.setObjectName("delaySlider_5")
        self.gridLayout_15.addWidget(self.delaySlider_5, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_15)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.resultLabel_5 = QtWidgets.QLabel(self.settingWidget)
        self.resultLabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.resultLabel_5.setObjectName("resultLabel_5")
        self.verticalLayout_11.addWidget(self.resultLabel_5)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.settingWidget)
        self.textBrowser_5.setStyleSheet("QTextBrowser{\n"
"    border:1px solid;\n"
"    border-color: rgb(166, 166, 166);\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_11.addWidget(self.textBrowser_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_10.setStretch(2, 1)
        self.verticalLayout_10.setStretch(3, 1)
        self.verticalLayout_10.setStretch(4, 1)
        self.verticalLayout_10.setStretch(5, 1)
        self.verticalLayout_10.setStretch(6, 10)
        self.horizontalLayout_2.addWidget(self.settingWidget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(150, 150, 150);\n"
"QTabWidget{\n"
"    margin:0px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.videoLabel = QtWidgets.QLabel(self.tab)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 641, 651))
        self.videoLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.videoLabel.setObjectName("videoLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.metricsLabel = QtWidgets.QLabel(self.tab_2)
        self.metricsLabel.setGeometry(QtCore.QRect(0, 1, 641, 541))
        self.metricsLabel.setObjectName("metricsLabel")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingLabel_5.setText(_translate("MainWindow", "设置setting"))
        self.modelLabel_5.setText(_translate("MainWindow", "模型选择"))
        self.modelCombo_5.setItemText(0, _translate("MainWindow", "yolov8n"))
        self.modelCombo_5.setItemText(1, _translate("MainWindow", "yolov11n"))
        self.modelCombo_5.setItemText(2, _translate("MainWindow", "plant detector"))
        self.modelCombo_5.setItemText(3, _translate("MainWindow", "car detector"))
        self.modelCombo_5.setItemText(4, _translate("MainWindow", "emotion detector"))
        self.loadModelBtn_5.setText(_translate("MainWindow", "加载模型"))
        self.inputLabel_5.setText(_translate("MainWindow", "输入选择"))
        self.videoButton_5.setToolTip(_translate("MainWindow", "视频video"))
        self.videoButton_5.setText(_translate("MainWindow", "..."))
        self.pictureButton_5.setToolTip(_translate("MainWindow", "图片picture"))
        self.pictureButton_5.setText(_translate("MainWindow", "..."))
        self.cameraButton_5.setToolTip(_translate("MainWindow", "摄像头camera"))
        self.cameraButton_5.setText(_translate("MainWindow", "..."))
        self.detectBtn_5.setText(_translate("MainWindow", "开始检测"))
        self.loULabel_5.setText(_translate("MainWindow", "loU"))
        self.confidenceLabel_5.setText(_translate("MainWindow", "置信度"))
        self.delayLabel_5.setText(_translate("MainWindow", "帧间延时"))
        self.resultLabel_5.setText(_translate("MainWindow", "结果统计"))
        self.videoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "实时检测"))
        self.metricsLabel.setText(_translate("MainWindow", "                                              在此显示各项指标"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "性能指标"))
